data_path: /home/visio-ai/PycharmProjects/CustomSFM/data/statue/
detector: sift
matching: FLANN
GoodP: False
dist_threshold: 0.5
max_dist: 15
sift_peak_threshold: 0.1
sift_edge_threshold: 10
sift_sigma: 1.6  #TODO implament it to sift
min_features: 8000